Part : 1

1: Load numerical columns from the dataset into Numpy arrays.

In [1]:
import numpy as np

import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")

print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...

In [3]:
age = df["Age"].dropna().to_numpy()
fare = df["Fare"].dropna().to_numpy()

2: Show array properties: shape, dtype, ndim . 

In [4]:
# Shape
print("Shape:", age.shape)

# Data Type
print("Data Type:", age.dtype)

# Number of Dimensions
print("Number of Dimensions:", age.ndim)

Shape: (332,)
Data Type: float64
Number of Dimensions: 1


3: Perform vectorized operations, such as:
        . Mean, Median, std of any numeric column
        . Element-wise addition  / multipultion  

In [5]:
print("Mean Age : " , np.mean(age))
print("Median Age :", np.median(age))
print("Std Age :", np.std(age))

Mean Age :  30.272590361445783
Median Age : 27.0
Std Age : 14.159835886272559


In [6]:
age_plus_2 = age + 2
print(age_plus_2)

[36.5  49.   64.   29.   24.   16.   32.   28.   20.   23.   48.   25.
 65.   49.   26.   37.   23.   29.   47.   57.   11.   23.   50.   52.
 24.   24.5  43.   52.   26.   35.   32.   20.5  23.   27.   41.   43.
 32.   47.   27.   47.   62.   38.   26.   29.   22.   30.   12.   37.
 27.   38.   19.   34.   20.   24.   15.   20.   49.   33.   62.   26.
 23.   31.   30.5  37.   34.5  57.   32.   26.    8.   69.   51.   29.
 20.    4.   24.   29.   27.   27.   78.   31.   22.   35.   45.   29.
 28.   18.   30.   23.   20.5  43.   38.   20.5  65.   20.    3.   38.
 31.   14.   37.   30.   19.   24.   44.   26.   34.   55.   45.   26.
 28.5  28.   25.   42.   12.   35.   63.   30.   44.   33.   24.   32.
 25.   62.5  38.   15.   26.   31.   25.   44.   28.    9.   28.   43.
 28.   50.   20.   24.   29.   25.   42.   17.   22.   56.   38.   66.
 32.   39.   20.   29.   42.   23.   19.   42.   36.   13.5  63.   10.
 35.    8.   20.   25.    2.33 49.   10.   27.   37.   26.   35.   27.
 34.  

In [9]:
fare_double = fare * 2
print(fare_double)

[  15.6584   14.       19.375    17.325    24.575    18.45     15.2584
   58.       14.4584   48.3      15.7916   52.      164.5334   52.
  122.35     55.4416   24.7      14.45     15.85     14.45    118.8
    6.3416   63.3666  122.7584  524.75     29.      123.9584   14.45
   61.       43.3584   52.       63.       41.15     46.9     115.5
   14.4584   16.1      17.325    19.      112.9916   26.8334   53.1
   15.7      26.      105.1084   15.85     59.4      15.5     152.5834
   31.8     120.       30.0666   46.      526.       31.1584   58.25
   15.7916   15.3      32.2     524.75     15.7916   27.       15.5
   15.45    524.75     42.       15.7584   84.8      57.075   526.
   15.5      15.7916   15.85     55.4416  423.      423.       16.1
   51.4      26.       15.5      30.4916  443.5584   52.       15.7916
   21.4166   28.9084   15.7584   16.1      15.5      46.       27.8
   15.55    104.       16.1      52.       15.5916  157.7      15.85
   15.7084   16.1     110.8834   52.  

4: Demonstrate:
          . Indexing
          . Boolean filtering
          . Slicing

In [ ]:
# indexing

print(age[0])   # first element
print(age[-1]) # last element
print(age[10:20])  # slice

34.5
38.5
[46. 23. 63. 47. 24. 35. 21. 27. 45. 55.]


In [ ]:
# Boolean Filtering

adult = age[age > 18]
print(adult)

[34.5 47.  62.  27.  22.  30.  26.  21.  46.  23.  63.  47.  24.  35.
 21.  27.  45.  55.  21.  48.  50.  22.  22.5 41.  50.  24.  33.  30.
 18.5 21.  25.  39.  41.  30.  45.  25.  45.  60.  36.  24.  27.  20.
 28.  35.  25.  36.  32.  22.  47.  31.  60.  24.  21.  29.  28.5 35.
 32.5 55.  30.  24.  67.  49.  27.  22.  27.  25.  25.  76.  29.  20.
 33.  43.  27.  26.  28.  21.  18.5 41.  36.  18.5 63.  36.  29.  35.
 28.  22.  42.  24.  32.  53.  43.  24.  26.5 26.  23.  40.  33.  61.
 28.  42.  31.  22.  30.  23.  60.5 36.  24.  29.  23.  42.  26.  26.
 41.  26.  48.  22.  27.  23.  40.  20.  54.  36.  64.  30.  37.  27.
 40.  21.  40.  34.  61.  33.  23.  47.  25.  35.  24.  33.  25.  32.
 60.  38.  42.  57.  50.  30.  21.  22.  21.  53.  23.  40.5 36.  21.
 21.  39.  20.  64.  20.  48.  55.  45.  45.  41.  22.  42.  29.  20.
 27.  24.  32.5 28.  19.  21.  36.5 21.  29.  30.  46.  26.  20.  28.
 40.  30.  22.  23.  36.  24.  30.  53.  36.  26.  30.  29.  32.  43.
 24.  64.  30.  55. 

In [14]:
#  Slicing 

print(age[:10]) 
print(age[50:60])
print(age[-10:])

[34.5 47.  62.  27.  22.  14.  30.  26.  18.  21. ]
[17. 32. 18. 22. 13. 18. 47. 31. 60. 24.]
[17.  43.  20.  23.  50.   3.  37.  28.  39.  38.5]


5: Use brodcasting to transform or scale value (e.g, normalize a column)

In [15]:
fare_norm = (fare - fare.mean()) / fare.std()
print(fare_norm)


[-0.49781052 -0.51265996 -0.46453181 -0.48288766 -0.41797062 -0.47281432
 -0.50139215 -0.11868068 -0.50855541 -0.2055352  -0.49661784 -0.17240513
  0.83522732 -0.17240513  0.45751401 -0.14158878 -0.41685136 -0.50863062
 -0.49609492 -0.50863062  0.42572705 -0.58123384 -0.07062774  0.46117086
  4.06063358 -0.37834884  0.47191575 -0.50863062 -0.09181846 -0.24978266
 -0.17240513 -0.07391031 -0.26955683 -0.21807091  0.3961786  -0.50855541
 -0.4938564  -0.48288766 -0.46788958  0.3737182  -0.39774874 -0.16255564
 -0.49743803 -0.40521106  0.30313144 -0.49609492 -0.10614497 -0.49922884
  0.72822613 -0.35327743  0.43647194 -0.36879842 -0.22612957  4.07182618
 -0.35902236 -0.11644216 -0.49661784 -0.50101966 -0.3496958   4.06063358
 -0.49661784 -0.39625699 -0.49922884 -0.49967655  4.06063358 -0.26194587
 -0.49691511  0.12128852 -0.1269632   4.07182618 -0.49922884 -0.49661784
 -0.49609492 -0.14158878  3.1495565   3.1495565  -0.4938564  -0.17777757
 -0.40521106 -0.49922884 -0.36499294  3.33363795 -0

In [18]:
age_scaled = age / age.max()
print(age_scaled)

[0.45394737 0.61842105 0.81578947 0.35526316 0.28947368 0.18421053
 0.39473684 0.34210526 0.23684211 0.27631579 0.60526316 0.30263158
 0.82894737 0.61842105 0.31578947 0.46052632 0.27631579 0.35526316
 0.59210526 0.72368421 0.11842105 0.27631579 0.63157895 0.65789474
 0.28947368 0.29605263 0.53947368 0.65789474 0.31578947 0.43421053
 0.39473684 0.24342105 0.27631579 0.32894737 0.51315789 0.53947368
 0.39473684 0.59210526 0.32894737 0.59210526 0.78947368 0.47368421
 0.31578947 0.35526316 0.26315789 0.36842105 0.13157895 0.46052632
 0.32894737 0.47368421 0.22368421 0.42105263 0.23684211 0.28947368
 0.17105263 0.23684211 0.61842105 0.40789474 0.78947368 0.31578947
 0.27631579 0.38157895 0.375      0.46052632 0.42763158 0.72368421
 0.39473684 0.31578947 0.07894737 0.88157895 0.64473684 0.35526316
 0.23684211 0.02631579 0.28947368 0.35526316 0.32894737 0.32894737
 1.         0.38157895 0.26315789 0.43421053 0.56578947 0.35526316
 0.34210526 0.21052632 0.36842105 0.27631579 0.24342105 0.5394